version: '3.8'

services:
  # Laravel app container
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: eventmanagementsystem-app
    volumes:
      - .:/var/www/html
    expose:
      - "80"   # Exposing HTTP port internally for Apache to access
    depends_on:
      - db
    networks:
      - app-network
    environment:
      - VIRTUAL_HOST=eventmanagement.algharabli-group.work

  # MySQL database container
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd@2025
      MYSQL_DATABASE: event_management
      MYSQL_USER: event_user
      MYSQL_PASSWORD: P@ssw0rd
    ports:
      - "3307:3306"
    networks:
      - app-network

  # Apache container with SSL enabled
  apache:
    image: httpd:latest
    container_name: apache_server
    volumes:
      - ./src:/var/www/html
      - ./apache-config/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./letsencrypt:/etc/letsencrypt  # Volume to store certs
    networks:
      - app-network
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app

  # Certbot container for Let's Encrypt SSL certificates
  certbot:
    image: certbot/certbot
    container_name: certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - app-network
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - ./apache-config:/etc/apache2/sites-available

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local
