version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: eventmanagementsystem-app
    volumes:
      - .:/var/www/html
    ports:
      - "8080:80"   # Exposing HTTP port
      - "8443:443" # Exposing HTTPS port
    depends_on:
      - db
    networks:
      - app-network
    environment:
      - VIRTUAL_HOST=eventmanagement.algharabli-group.work

  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd@2025
      MYSQL_DATABASE: event_management
      MYSQL_USER: event_user
      MYSQL_PASSWORD: P@ssw0rd
    ports:
      - "3307:3306"
    networks:
      - app-network


networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local
